### ISSUE TITLE
[DatabaseApp] Projection Helper

### ISSUE THREAD

**Issue by pavel-b-novikov** [Grafeeva/nsudotnet#1]
Ну тут вы сами напросились. 
Projection Helper написал я.
Сам б-г велел спросить - а что же все-таки он делает и почему вы его задействовали?

Пожалуйста, детально, последовательно, с изложением проблемы.

**Comment by Grafeeva** [comment]
Начнем с того что это еще не окончательная версия программы :)

Мы подумали что вы не будете против заимствования кода.
Тем более что ничего более изящного для того чтобы связать агрегаты у сущностей я не придумала.  
По крайней мере такого, чтобы получилось красивое обобщенное программирование с generic интерфейсами для логики. 
(Собственно первоначальным решением было написать для каждой сущности интерфейс в котором были бы методы для извлечения сущности вместе с агрегатами, но тогда получилось бы большое количество интерфейсов, что явно не гуд. Следующий шаг: написание generic интерфейса и проставление аннотации над теми полями, которые являются агрегатами, и вызове Include() с полями, полученными с помощью рефлексии.Могу предоставить этот вариант если хотите, где-то он у меня сохранился. А потом мы заглянули в ваш sample и увидели подходящее решение, фактически тоже самое что и в последнем варианте, но не приходится каждый раз вытаскивать метаданные.)

Ваш Helper как раз и занимается тем что генерирует последовательную цепочку Include()

**Comment by pavel-b-novikov** [comment]
Вам кто-то помогает, или вы сами так шарите? О_о
