### ISSUE TITLE
[DatabaseApp] Ошибка IoC

### ISSUE THREAD

**Issue by pavel-b-novikov** [Grafeeva/nsudotnet#2]
У вас везде закомменчен в конструкторах сервисов DbContext.

Признайтесь - вы ниасилили тоже пихнуть его в IoC-контейнер?

**Comment by Grafeeva** [comment]
Каюсь, с этим мы не разбирались на данный момент.
Исправим.

**Comment by Grafeeva** [comment]
Done

**Comment by pavel-b-novikov** [comment]
> builder.RegisterType<PhilharmonicContext>().As<DbContext>();

(facepalm)
Расскажите теперь в какой момент у вас будет создаваться новый инстанс DbContext-а?

**Comment by pavel-b-novikov** [comment]
[1:39:25] Pavel B. Novikov: вот прошарьте как этот механизм работает
[1:39:25] Pavel B. Novikov: и будет 5

**Comment by Grafeeva** [comment]
builder.RegisterType().As();

По умолчанию используется .InstancePerDependency(), а это означает что при каждом новом вызове создавался новый объект типа PhilharmonicContext, следовательно для каждого инстанцированного класса логики был свой экземпляр типа PhilharmonicContext, т.е. было несколько connection к БД. А это плохо.
.SingleInstance() решит данную проблему так как будет существовать единственный экземпляр.

В Autofac.MVC есть еще также .InstancePerHttpRequest() - один экземпляр на HttpRequest

**Comment by pavel-b-novikov** [comment]
зачтено
